<html>
    <head>
    	<style>
    	</style>
    </head>
    <body>
    	<div class="conteudo">
    		<!-- <h1>COLÉGIO CORA CORALINA</h1> -->
    		Boletim Escolar Ensino Fundamental Cilo - 1 / 2016

    		<div class="boletim">
    			<table border="1">
    				<thead>
    					<tr>
    						<td colspan="19">
    							Aluno (a): GIOVANA BARBOSA CASSIANO       Número: 03       Turma: 1º Ano A       R.a. - 11847784-01
    						</td>
    					</tr>
    					<tr>
    						<td>
    							Disciplinas
    						</td>
    						<td>
    							NOTAS DO 1º BIMESTRE
    						</td>
    						<td>
    							AULAS DADAS NO BIMESTRE
    						</td>
    						<td>
    							FALTAS DO BIMESTRE
    						</td>
    						<td>
    							NOTAS DO 2º BIMESTRE
    						</td>
    						<td>
    							AULAS DADAS NO BIMESTRE
    						</td>
    						<td>
    							FALTAS DO BIMESTRE
    						</td>
    						<td>
    							NOTAS DO 3º BIMESTRE
    						</td>
    						<td>
    							AULAS DADAS NO BIMESTRE
    						</td>
    						<td>
    							FALTAS DO BIMESTRE
    						</td>
    						<td>
    							NOTAS DO 4º BIMESTRE
    						</td>
    						<td>
    							AULAS DADAS NO BIMESTRE
    						</td>
    						<td>
    							FALTAS DO BIMESTRE
    						</td>
    						<td>
    							MÉDIA ANUAL
    						</td>
    						<td>
    							TOTAL DE FALTAS
    						</td>
    						<td>
    							RECUPERAÇÃO FINAL
    						</td>
    						<td>
    							MÉDIA FINAL
    						</td>
    						<td>
    							SITUAÇÃO FINAL
    						</td>
    					</tr>
    				</thead>
    				<tbody>
    					<tr>
    						<td>
    							ARTE
    						</td>
    						<td>
    							10,0
    						</td>
    						<td>
    							10,0
    						</td>
    						<td>
    							10,0
    						</td>
    						<td>
    							10,0
    						</td>
    						<td>
    							10,0
    						</td>
    						<td>
    							10,0
    						</td>
    						<td>
    							10,0
    						</td>
    						<td>
    							10,0
    						</td>
    						<td>
    							10,0
    						</td>
    						<td>
    							10,0
    						</td>
    						<td>
    							10,0
    						</td>
    						<td>
    							10,0
    						</td>
    						<td>
    							10,0
    						</td>
    						<td>
    							10,0
    						</td>
    						<td>
    							10,0
    						</td>
    						<td>
    							10,0
    						</td>
    						<td>
    							10,0
    						</td>
    					</tr>
    					<tr>
    						<td>
    							CIÊNCIAS
    						</td>
    						<td>
    							10,0
    						</td>
    						<td>
    							10,0
    						</td>
    						<td>
    							10,0
    						</td>
    						<td>
    							10,0
    						</td>
    						<td>
    							10,0
    						</td>
    						<td>
    							10,0
    						</td>
    						<td>
    							10,0
    						</td>
    						<td>
    							10,0
    						</td>
    						<td>
    							10,0
    						</td>
    						<td>
    							10,0
    						</td>
    						<td>
    							10,0
    						</td>
    						<td>
    							10,0
    						</td>
    						<td>
    							10,0
    						</td>
    						<td>
    							10,0
    						</td>
    						<td>
    							10,0
    						</td>
    						<td>
    							10,0
    						</td>
    						<td>
    							10,0
    						</td>
    					</tr>
    					<tr>
    						<td>
    							HISTÓRIA
    						</td>
    						<td>
    							10,0
    						</td>
    						<td>
    							10,0
    						</td>
    						<td>
    							10,0
    						</td>
    						<td>
    							10,0
    						</td>
    						<td>
    							10,0
    						</td>
    						<td>
    							10,0
    						</td>
    						<td>
    							10,0
    						</td>
    						<td>
    							10,0
    						</td>
    						<td>
    							10,0
    						</td>
    						<td>
    							10,0
    						</td>
    						<td>
    							10,0
    						</td>
    						<td>
    							10,0
    						</td>
    						<td>
    							10,0
    						</td>
    						<td>
    							10,0
    						</td>
    						<td>
    							10,0
    						</td>
    						<td>
    							10,0
    						</td>
    						<td>
    							10,0
    						</td>
    					</tr>
    					<tr>
    						<td>
    							INGLÊS
    						</td>
    						<td>
    							10,0
    						</td>
    						<td>
    							10,0
    						</td>
    						<td>
    							10,0
    						</td>
    						<td>
    							10,0
    						</td>
    						<td>
    							10,0
    						</td>
    						<td>
    							10,0
    						</td>
    						<td>
    							10,0
    						</td>
    						<td>
    							10,0
    						</td>
    						<td>
    							10,0
    						</td>
    						<td>
    							10,0
    						</td>
    						<td>
    							10,0
    						</td>
    						<td>
    							10,0
    						</td>
    						<td>
    							10,0
    						</td>
    						<td>
    							10,0
    						</td>
    						<td>
    							10,0
    						</td>
    						<td>
    							10,0
    						</td>
    						<td>
    							10,0
    						</td>
    					</tr>
    				</tbody>
    			</table>
    		</div>
    	</div>

        <?php // echo "<pre>";print_r($resultado);die; ?>
    </body>
</html>